In [1]:
import numpy as np

## Creating numpy arrays

In [3]:
# Python list
pyList = [1,2,3]
type(pyList)

list

In [4]:
# Numpy array
arr = np.array(pyList)
type(arr)

numpy.ndarray

In [6]:
# Create numpy array from within a range
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10, 2)

array([0, 2, 4, 6, 8])

In [11]:
# Create multi-dimensional numpy array
np.zeros(shape=(10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(shape=(10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# Generate numpy array with random integers (start, end, size)
np.random.seed(100)
arr = np.random.randint(0,100,10)
print(arr)

[ 8 24 67 87 79 48 10 94 52 98]


In [27]:
print("Max number is ", arr.max())
print("Min number is ", arr.min())
print("Max number is at position ", arr.argmax())
print("The mean is ", arr.mean())

Max number is  98
Min number is  8
Max number is at position  9
The mean is  56.7


In [28]:
arr.shape

(10,)

In [29]:
# reshape numpy array 
arr.reshape(2,5)

array([[ 8, 24, 67, 87, 79],
       [48, 10, 94, 52, 98]])

## Indexing

In [31]:
matrix = np.arange(0,100).reshape(10,10)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
row = 0
col = 1

In [33]:
matrix[0, 1]

1

## Get Column

In [34]:
matrix[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

## Get Row

In [42]:
matrix[9,:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])